"""changed size of password_hash column

Revision ID: 21490fe68ed9
Revises: 0411156e88da
Create Date: 2025-08-28 12:22:57.536306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21490fe68ed9'
down_revision = '0411156e88da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=254),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
